FROM node:latest

WORKDIR /frontend

# copy dependency definitions
COPY package.json /frontend/package.json
COPY package-lock.json /frontend/package-lock.json

# install dependencies
RUN npm ci

# set non-root user to run spotihue UI
RUN useradd -m -s /bin/bash spotihue_frontend
RUN groupadd docker
RUN usermod -aG docker spotihue_frontend
RUN chown -R spotihue_frontend /frontend/

USER spotihue_frontend:docker

# expose port
EXPOSE 3000

CMD ["npm", "start"]
