FROM node:latest

RUN mkdir /frontend
WORKDIR /frontend

# copy dependency definitions
COPY package.json /frontend/package.json
COPY package-lock.json /frontend/package-lock.json

# install dependencies
RUN npm ci

# copy necessary app code
COPY . /frontend

# expose port
EXPOSE 3000

# Set non-root user to run spotihue UI
RUN useradd -U -m -s /bin/bash spotihue_frontend
RUN chown -R -v :spotihue_frontend /frontend/
USER spotihue_frontend:spotihue_frontend

CMD ["npm", "start"]
