FROM python:3.10

RUN mkdir /code
WORKDIR /code

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt