FROM python:3.10

ENV PYTHONUNBUFFERED=1

RUN mkdir /backend
WORKDIR /backend

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install --upgrade pip

COPY requirements.txt /backend/
RUN pip install -r requirements.txt

# set non-root user to run celery and spotihue API
RUN useradd -U -m -s /bin/bash spotihue_backend
RUN chown -R -v :spotihue_backend /backend/
USER spotihue_backend:spotihue_backend

EXPOSE 8000
EXPOSE 8888
