FROM python:3.10

RUN mkdir /code
WORKDIR /code

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY backend/spotihue ./code/
COPY backend/main.py /code/
COPY backend/requirements.txt /code/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:fast_app", "--host", "0.0.0.0", "--port", "8000"]